version: "3.8"

volumes:
  chairs:
  omnifood:
  natours:
  trillo:
  nexter:


services:
  chairs-service:
    container_name: chairs-service-c
    build:
      context: ./webpages/chairs
    ports:
      - "5000:5000"
    volumes:
      - chairs:/chairs
    restart: always

  omnifood-service:
    container_name: omnifood-service-c
    build:
      context: ./webpages/omnifood
    ports:
      - "5001:5001"
    volumes:
      - omnifood:/omnifood
    restart: always

  natours-service:
    container_name: natours-service-c
    build:
      context: ./webpages/natours
    ports:
      - "5002:5002"
    volumes:
      - natours:/natours
    restart: always

  trillo-service:
    container_name: trillo-service-c
    build:
      context: ./webpages/trillo
    ports:
      - "5003:5003"
    volumes:
      - trillo:/trillo
    restart: always

  nexter-service:
    container_name: nexter-service-c
    build:
      context: ./webpages/nexter
    ports:
      - "5004:5004"
    volumes:
      - nexter:/nexter
    restart: always